import { Link, useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

const PRIVACY_POLICY_VERSION = "2026-08-25";
const PRIVACY_POLICY_LAST_UPDATED = "25 August 2026";

const Section = ({ title, children }) => <section><h2 className="text-xl font-semibold text-slate-900 mb-2">{title}</h2><div className="text-slate-700 space-y-2">{children}</div></section>;

export default function PrivacyPolicy() {
  const navigate = useNavigate();
  const back = () => window.history.length > 1 ? navigate(-1) : navigate(createPageUrl("Landing"));
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50"><div className="max-w-4xl mx-auto px-6 py-10">
      <Button variant="ghost" size="sm" className="mb-4" onClick={back}><ArrowLeft className="w-4 h-4 mr-2" />Back</Button>
      <h1 className="text-3xl font-bold text-slate-900 mb-2">Privacy Policy</h1>
      <p className="text-slate-600 mb-8">Version {PRIVACY_POLICY_VERSION} · Last updated {PRIVACY_POLICY_LAST_UPDATED}</p>
      <div className="bg-white rounded-xl shadow-lg p-6 space-y-7">
        <Section title="1. Controller and contact"><p>FACT: Find a Coach Today (“FACT”) is the controller for personal information collected through this marketplace. Email privacy questions or rights requests to <a className="text-blue-600 underline" href="mailto:support@findacoachtoday.com">support@findacoachtoday.com</a>.</p></Section>
        <Section title="2. Information we use"><ul className="list-disc ml-6 space-y-1"><li>Account, identity, date of birth, age confirmation and contact details.</li><li>For a child participant: name, date of birth, guardian relationship and consent, emergency contact, and only the medical, accessibility or safeguarding information needed for the session.</li><li>Coach profile, qualification, insurance and background-check evidence and review outcomes.</li><li>General location, preferences, availability, session, booking, payment-status and payout information.</li><li>Messages, reviews, support requests, disputes, safeguarding reports and investigation records.</li><li>Login, device, IP, security, diagnostic, cookie and service-usage data.</li><li>Information provided by another booking participant, payment provider, identity provider or relevant authority.</li></ul></Section>
        <Section title="3. Purposes and lawful bases"><ul className="list-disc ml-6 space-y-1"><li><strong>Contract:</strong> accounts, coach discovery, bookings, messages, payments, refunds and support.</li><li><strong>Legal obligations:</strong> accounting, tax, fraud prevention, lawful requests and consumer-rights compliance.</li><li><strong>Legitimate interests:</strong> platform security, service improvement, dispute handling, safeguarding and protecting users, balanced against individual rights.</li><li><strong>Consent:</strong> optional marketing and any processing where consent is specifically requested; consent can be withdrawn at any time.</li><li><strong>Vital interests:</strong> limited emergency disclosures where necessary to protect life.</li></ul><p>Where safeguarding or coach checks involve special-category or criminal-offence information, FACT applies an additional lawful condition where required, restricts access and follows an appropriate policy and retention process.</p></Section>
        <Section title="4. Who receives information"><p>Information is shared only as necessary with the relevant client or coach; Stripe and payment partners; hosting, database, email, monitoring, storage and identity providers; professional advisers; and police, social care, The FA, County FAs, regulators or courts where lawful and appropriate. We do not sell personal information. Public coach profiles exclude email, telephone number, full address and verification documents.</p></Section>
        <Section title="5. International transfers"><p>Some suppliers may process information outside the UK. FACT uses applicable adequacy regulations or contractual safeguards such as the UK International Data Transfer Agreement or UK Addendum. Contact us for information about relevant safeguards.</p></Section>
        <Section title="6. Retention"><ul className="list-disc ml-6 space-y-1"><li>Active account data is kept while the account operates; core account, booking, payment and dispute records may be retained for up to six years after closure or the transaction.</li><li>Technical and security logs are normally retained for up to 12 months unless needed for an investigation.</li><li>Coach evidence is retained only while required for verification and safeguarding review; rejected or superseded document copies are normally deleted within six months, while status and audit evidence may be kept for up to six years.</li><li>Safeguarding records are retained according to risk, legal requirements and the needs of affected people, with periodic review rather than automatic deletion that could endanger someone or destroy necessary evidence.</li><li>Marketing preferences are kept until withdrawal, with a minimal suppression record retained to honour opt-out requests.</li></ul></Section>
        <Section title="7. Your rights"><p>Depending on the processing, you may request access, correction, deletion, restriction or portability, object to processing, and withdraw consent. The right to object applies particularly to direct marketing and processing based on legitimate interests. Email <a className="text-blue-600 underline" href="mailto:support@findacoachtoday.com">support@findacoachtoday.com</a>; identity checks may be required.</p><p>You may complain to the Information Commissioner’s Office at <a className="text-blue-600 underline" href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noreferrer">ico.org.uk/make-a-complaint</a>, telephone 0303 123 1113, or by post to the ICO, Wycliffe House, Water Lane, Wilmslow, Cheshire SK9 5AF.</p></Section>
        <Section title="8. Children"><p>FACT accounts are for adults aged 18 or over. A parent or legal guardian must manage bookings for an under-18 player. Child participants do not receive accounts or private messaging. Their details are visible only to the guardian, relevant coach and authorised FACT staff where needed to arrange or safeguard the session. Do not place unnecessary information about a child in a public profile or message. We use child-related information only to arrange and safeguard the session and apply privacy settings designed to minimise exposure.</p></Section>
        <Section title="9. Security, cookies and automated decisions"><p>FACT uses access controls, encryption in transit, monitoring and restricted administrator permissions. No internet service can promise absolute security. Essential cookies support authentication and security. Optional analytics or marketing cookies must not be used without the required choice. FACT does not currently make solely automated decisions producing legal or similarly significant effects.</p></Section>
        <Section title="10. Changes"><p>We review this notice when data use, suppliers or law changes. Material new uses will be explained before they begin, and the fixed version date will be updated.</p></Section>
        <div className="pt-4 border-t flex flex-wrap gap-4"><Link to={createPageUrl("Terms")} className="text-blue-600 hover:underline">Terms and Conditions</Link><Link to={createPageUrl("SafeguardingPolicy")} className="text-blue-600 hover:underline">Safeguarding Policy</Link></div>
      </div>
    </div></div>
  );
}
