import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { POLICY_LAST_UPDATED, POLICY_VERSION } from "@/lib/policyConstants";

export default function SafeguardingPolicy() {
  return <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50"><div className="max-w-4xl mx-auto px-6 py-10">
    <h1 className="text-3xl font-bold text-slate-900">Safeguarding Policy</h1><p className="text-slate-600 mt-2 mb-8">Version {POLICY_VERSION} · Last updated {POLICY_LAST_UPDATED}</p>
    <div className="bg-white rounded-xl shadow-lg p-6 space-y-7 text-slate-700">
      <section><h2 className="text-xl font-semibold text-slate-900 mb-2">Our commitment</h2><p>FACT is committed to the welfare of children, young people and adults at risk. Safety takes priority over commercial or reputational interests. Coaches, clients, parents, guardians and administrators share responsibility for respectful and safe sessions.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900 mb-2">Accounts and sessions involving under-18s</h2><ul className="list-disc ml-6 space-y-1"><li>Only adults aged 18 or over may hold a FACT account.</li><li>A parent or legal guardian must make and manage bookings for an under-18 player and arrange appropriate supervision, transport and emergency information.</li><li>Coaches must maintain professional boundaries, avoid private or inappropriate communication and follow applicable FA safeguarding guidance.</li><li>Sessions should use suitable venues and equipment. One-to-one situations involving a child should be visible, interruptible and agreed with the responsible adult.</li></ul></section>
      <section><h2 className="text-xl font-semibold text-slate-900 mb-2">Reporting a concern</h2><p>If anyone is in immediate danger, call 999. For a non-emergency concern, use <Link className="text-blue-600 underline" to={createPageUrl("SafeguardingReport")}>Report Concern</Link> or email <a className="text-blue-600 underline" href="mailto:support@findacoachtoday.com">support@findacoachtoday.com</a>. You may also contact local police or children’s social care. Football-related concerns can be reported to The FA Safeguarding Team on 0800 169 1863 or safeguarding@thefa.com.</p><p className="mt-2">Stay calm, listen, record facts, preserve relevant messages and do not investigate or confront the person reported. Do not promise confidentiality; information may need to be shared to protect someone.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900 mb-2">How FACT responds</h2><p>FACT triages reports by risk, records actions, restricts access to case information and may suspend accounts or communication immediately. We may seek further information and refer matters to police, social care, The FA, a County FA or another appropriate authority. FACT cannot determine criminal guilt and will not interfere with an external investigation.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900 mb-2">Coach vetting and monitoring</h2><p>Coaches are not publicly bookable until required qualification and current background-check evidence has been reviewed. Expiry, changed evidence, a serious concern or unreliable information can remove verification or cause suspension. Checks reduce risk but never replace supervision, reporting or professional conduct.</p></section>
      <section><h2 className="text-xl font-semibold text-slate-900 mb-2">Confidentiality and records</h2><p>Reports are shared on a need-to-know basis. FACT keeps safeguarding records securely for a period based on risk, legal requirements and the interests of affected people. Reporters will receive an acknowledgement, but privacy and investigation integrity may limit the detail FACT can provide about action taken.</p></section>
      <div className="pt-4 border-t flex flex-wrap gap-4"><Link to={createPageUrl("SafeguardingReport")} className="text-blue-600 underline">Submit a concern</Link><Link to={createPageUrl("Terms")} className="text-blue-600 underline">Terms</Link><Link to={createPageUrl("PrivacyPolicy")} className="text-blue-600 underline">Privacy</Link></div>
    </div>
  </div></div>;
}
